sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LeBEumpaBEbIM7bxJUScjgLF2YMBnwjqytoGN7KuAtQEvefXUqyVUWeKE0tDZ3kLK/KuxfQi3poyKuHrZhTmSMIqRlOkA7iZ7Qxwf6tyBKWhKJpf33uAhZt0UaKzXiVkbTE3nMzTDVdD9KqG03qg63iTQPMpDD5rJKK80JhH1ASD7n60MTEh9NLb3o4zJsnCU+rePTONa/gkSDb9OEFWgGGnDBJSlK4CdfxQrExnozXi2AG2rnKJr2/RngfvTskOyo5SrWubA5O0zK4vlZwNBwrumOsqOD659aUIHLPNplHikb2YoXLm1fQQKALo/b9cV5H3f7yzw6crXa0Xs3zA/lNX+PYx5FVShXZ6KIPT17pvHhvyZTn8aRJklkmHWlOLMSP/AqQJvmRTPIFiEk7b/LLq2D9zKyljNQAR90pwcxo8NSYe0QuXhrV8fKXwIptYIXI7tF7acM7vvh39LC7mlJuskh3hqAV0nRFw26/w8VGU0kuDpxCR0ak/yvL7zdKpwZAPm7S85I3CgGyBHU8eq7kgO5MbcyCbxPXbXNbihNY4f9/ckojJWDhgMAgiS26SsHIfJ60xCTn99UyYP/gWIFED+H0gDmPBr+wuTi6rFooTJegn4ytEUExiwSXvh5C0rd/f9hl4kvYiYBZYuKHc6Oc2kArupO9dFOqBSg2tPlY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Prodigal-Judge_5129
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy